### ISSUE TITLE
RuntimeError: output with shape [1, 1, 16, 16] doesn't match the broadcast shape [1, 8, 16, 16]

### ISSUE THREAD

**Issue by BMontens** [lucidrains/x-transformers#163]
When I use `alibi_pos_bias = True` I get:
`RuntimeError: output with shape [1, 1, 16, 16] doesn't match the broadcast shape [1, 8, 16, 16]`

Code:
```
import torch
from x_transformers import ContinuousTransformerWrapper, Encoder

MAX_SEQ_LEN = 16
IN_DIM = 128 # dimension of the input
OUT_DIM = 128 # dimension of each codebook vector
ATTN_DIM = 128 # dimension of the transformer
ATTN_DEPTH = 6 # depth of the transformer
ATTN_DIM_HEAD = 16 # dimension of each head of the transformer

heads = ATTN_DIM // ATTN_DIM_HEAD
model = ContinuousTransformerWrapper(
    dim_in = IN_DIM,
    dim_out = OUT_DIM,
    max_seq_len = MAX_SEQ_LEN,
    attn_layers = Encoder(
        dim = ATTN_DIM,
        depth = ATTN_DEPTH,
        heads = heads,
        attn_flash = True, # just set this to True if you have pytorch 2.0 installed
        alibi_pos_bias = True, # turns on ALiBi positional embedding
    )
)

x = torch.randn((1, 16, 128))

model(x)
```

But it works if I remove alibi

**Comment by lucidrains** [comment]
@BMontens could you also show the full trace?

it runs on my machine

**Comment by BMontens** [comment]
```
Traceback (most recent call last):
  File "/media/USRNAME/Storage/Code/AI/test.py", line 49, in <module>
    quantized, commit_loss = extractor(input)
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/USRNAME/Storage/Code/AI/test.py", line 33, in forward
    x = self.transformer(input)
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 1467, in forward
    x, intermediates = self.attn_layers(x, mask = mask, mems = mems, return_hiddens = True, **kwargs)
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 1124, in forward
    out, inter = block(x, mask = mask, context_mask = self_attn_context_mask, attn_mask = attn_mask, rel_pos = self.rel_pos, rotary_pos_emb = rotary_pos_emb, prev_attn = prev_attn, mem = layer_mem)
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 827, in forward
    out, intermediates = self.attend(
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/attend.py", line 299, in forward
    out, intermediates = self.attend(
  File "/home/USRNAME/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/attend.py", line 204, in forward
    return self.flash_attn(q, k, v, mask = mask, attn_bias = attn_bias)
  File "/home/USRNAME/.pyenv/versions/3.10.10/lib/python3.10/site-packages/x_transformers/attend.py", line 174, in flash_attn
    out = F.scaled_dot_product_attention(
RuntimeError: output with shape [1, 1, 16, 16] doesn't match the broadcast shape [1, 8, 16, 16]
```

**Comment by lucidrains** [comment]
which version of x-transformers are you on? can you try updating to the latest version? try [the latest](https://github.com/lucidrains/x-transformers/commit/503fd484d6f2a380198e42496ea43e384289a784)

**Comment by lucidrains** [comment]
alright, i'm closing, i think it should be fixed haha

**Comment by BMontens** [comment]
Successfully installed vector_quantize_pytorch-1.6.28

Still not working on this version

**Comment by lucidrains** [comment]
@BMontens lol, an emoji response

ok, happy training!
